services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-cache:/go
    environment:
      - CGO_ENABLED=0
      - GOCACHE=/go/cache
      - GOMODCACHE=/go/mod

  test:
    extends: 
      service: dev
    command: go test -v -race -coverprofile=/app/coverage.txt -covermode=atomic ./...
    environment:
      - CGO_ENABLED=1

  lint:
    extends:
      service: dev
    command: golangci-lint run --timeout=5m

  fmt:
    extends:
      service: dev
    command: gofumpt -l .

  goreleaser:
    profiles:
      - release
    image: goreleaser/goreleaser:latest@sha256:812dda67b334c99b80571720977e6eee7e977a57e6b8e29a8b0c680a750300d7
    volumes:
      - .:/app
    working_dir: /app

volumes:
  go-cache:
