services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-cache:/go
    environment:
      - CGO_ENABLED=0
      - GOCACHE=/go/cache
      - GOMODCACHE=/go/mod

  test:
    extends: 
      service: dev
    command: go test -v -race -coverprofile=/app/coverage.txt -covermode=atomic ./...
    environment:
      - CGO_ENABLED=1

  lint:
    extends:
      service: dev
    command: golangci-lint run --timeout=5m

  fmt:
    extends:
      service: dev
    command: gofumpt -l .

  goreleaser:
    profiles:
      - release
    image: goreleaser/goreleaser:latest@sha256:c5c07c3c3d8f50d027845b34791d41ff30901bfee52b2d2dcee5533a32840282
    volumes:
      - .:/app
    working_dir: /app

volumes:
  go-cache:
