services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-cache:/go
    environment:
      - CGO_ENABLED=0
      - GOCACHE=/go/cache
      - GOMODCACHE=/go/mod

  test:
    extends: 
      service: dev
    command: go test -v -race -coverprofile=/app/coverage.txt -covermode=atomic ./...
    environment:
      - CGO_ENABLED=1

  lint:
    extends:
      service: dev
    command: golangci-lint run --timeout=5m

  fmt:
    extends:
      service: dev
    command: gofumpt -l .

  goreleaser:
    profiles:
      - release
    image: goreleaser/goreleaser:latest@sha256:f7f4c58b0259a37104ada4db42f2781883ac231e304164f1f352f8a084939dbd
    volumes:
      - .:/app
    working_dir: /app

volumes:
  go-cache:
