services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-cache:/go
    environment:
      - CGO_ENABLED=0
      - GOCACHE=/go/cache
      - GOMODCACHE=/go/mod

  test:
    extends: 
      service: dev
    command: go test -v -race -coverprofile=/app/coverage.txt -covermode=atomic ./...

  lint:
    extends:
      service: dev
    command: golangci-lint run --timeout=5m

  fmt:
    extends:
      service: dev
    command: gofumpt -l .

  # Production application service - only used for local development of the app itself
  app:
    profiles:
      - app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PROJECT_ID
      - TOPIC_ID
      - BUILDKITE_WEBHOOK_TOKEN
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS:-}:/tmp/credentials.json:ro

  # Release tooling
  goreleaser:
    profiles:
      - release
    image: goreleaser/goreleaser:latest
    volumes:
      - .:/app
    working_dir: /app

volumes:
  go-cache:
