apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: monitoring
data:
  alerts.yml: |
    groups:
      - name: buildkite-webhook
        rules:
          - alert: HighErrorRate
            expr: rate(buildkite_errors_total[5m]) > 0.1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High error rate in webhook service
              description: "Error rate is {{ $value }} per second for the past 5 minutes"

          - alert: HighAuthFailures
            expr: rate(buildkite_webhook_auth_failures_total[5m]) > 0.05
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High rate of authentication failures
              description: "Auth failure rate is {{ $value }} per second"

          - alert: HighLatency
            expr: histogram_quantile(0.95, rate(buildkite_webhook_request_duration_seconds_bucket[5m])) > 1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High webhook processing latency
              description: "95th percentile latency is {{ $value }} seconds"

          - alert: PubSubPublishFailures
            expr: rate(buildkite_pubsub_publish_requests_total{status="error"}[5m]) > 0.1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High rate of Pub/Sub publish failures
              description: "Pub/Sub failure rate is {{ $value }} per second"

          - alert: RateLimitingTriggered
            expr: rate(buildkite_rate_limit_exceeded_total[5m]) > 0.1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High rate of rate limit triggers
              description: "Rate limit exceeded {{ $value }} times per second"
