# Generate base64 encoded values with:
# echo -n "value-to-encode" | base64
apiVersion: v1
kind: Secret
metadata:
  name: buildkite-webhook-secrets
  namespace: buildkite-webhook
type: Opaque
data:
  # Buildkite webhook token
  buildkite-token: ${BUILDKITE_WEBHOOK_TOKEN_BASE64}

  # GCP service account key for Pub/Sub and BigQuery access
  gcp-service-account.json: ${GCP_SERVICE_ACCOUNT_JSON_BASE64}

  # TLS certificate and key (if not using cert-manager)
  tls.crt: ${TLS_CERT_BASE64}
  tls.key: ${TLS_KEY_BASE64}
